### PR TITLE
Replace calls with Kubernetes python client

### PR DESCRIPTION
**Pull request by chaitanyaenr**
Reused the code from https://github.com/chaos-kubox/krkn/pull/256.
    
 Co-authored-by Sanja Bonic (sanjacodes)

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
Need to test this patch on Kubernetes cluster before merging.

**Comment by janosdebugs** [comment]
Lpoks good, but do you maybe want to add a Co-authored-by to your commit?

**Review by sanjacodes — APPROVED** [review]

**Review by janosdebugs — APPROVED** [review]
Looks good, but do you maybe want to add a Co-authored-by to your commit?

**Comment by chaitanyaenr** [comment]
> Looks good, but do you maybe want to add a Co-authored-by to your commit?

Done. Thanks.

**Pull request merged**
